# Generated by Django 2.2.5 on 2019-12-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_flor_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flor',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
