# Generated by Django 2.2.7 on 2019-12-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191210_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
