# Generated by Django 2.2.7 on 2019-12-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191212_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='slug',
            field=models.SlugField(default='producto-flor'),
            preserve_default=False,
        ),
    ]
