# Generated by Django 2.2.7 on 2019-12-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_flor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flor',
            name='slug',
        ),
    ]
