# Generated by Django 2.2.7 on 2019-12-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_flor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
