# Generated by Django 2.2.7 on 2019-12-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191215_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
